Replace the type of client_id and actor_id in protobuf
yorkie-team/yorkie pull request #145
Opened 2021-01-27 15:29 UTC by autumn-n

**What this PR does / why we need it**:

> A 24 bytes hex-encoded string can be replaced with a 12 bytes of array to reduce size of marshalled data with Protobuf.

**Which issue(s) this PR fixes**:

> Fixes #36 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE, It just reduce the size of data between client and server.
```

**Additional documentation**:

```docs

```

**Checklist**:
- [x] Added relevant tests or not required
- [x] Didn't break anything

2021-01-28 02:45 UTC, hackerwins commented
@autumn-n Thank you for sending PR. We'll review this soon.

2021-01-31 05:25 UTC, dc7303 requested changes
Thanks for the wonderful work :+1:
I left some amendments and questions. After checking, please be honest with your opinion.

## Question
I think the modify the JS SDK also needs to be done to profile this PR. If you let me know if you're modifying the JS SDK, I think we'll see how we can help.
Are you modifying the JS SDK?

## About test
How about adding a unit test for the added method?
I think it would be nice to add the normal case and exception cases of the method. This is because it will serve as a document and a safeguard for developers who analyze and modify this method in the future.

2021-01-31 11:37 UTC, autumn-n commented on pkg/document/time/actor_id.go
> +		return []byte{}
NP, I will follow it. Thanks for letting me know.

2021-01-31 11:59 UTC, autumn-n commented
@dc7303 Thanks for your comments

> ## Question
> I think the modify the JS SDK also needs to be done to profile this PR. If you let me know if you're modifying the JS SDK, I think we'll see how we can help.
> Are you modifying the JS SDK?

Meanwhile, I'm already done. Once review has done, I will send a PR of JS SDK too.

> ## About test
> How about adding a unit test for the added method?
> I think it would be nice to add the normal case and exception cases of the method. This is because it will serve as a document and a safeguard for developers who analyze and modify this method in the future.

Yes, you are right. I should have done that before. I'm gonna do it. In addition, It would be also great if there were more tests to figure out the intentions for new contributors.

2021-02-01 12:50 UTC, dc7303 approved these changes
LGTM 👍 😄

2021-02-01 18:45 UTC, hackerwins approved these changes
LGTM. Thanks for the contribution.

2021-02-01 18:45 UTC, merged