add command-line flags for agent command(#152)
yorkie-team/yorkie pull request #167
Opened 2021-03-28 16:33 UTC by computerphilosopher

**What this PR does / why we need it**:
Add flags that can set all configurations of Agent.
**Which issue(s) this PR fixes**:

Fixes #152 

**Special notes for your reviewer**:

It assigns command-line flags directly to the configuration struct variable. 

timeout-second variables don't be assigned directly from command-line flags. Because to assign duration variable from command-line arguments, users have to specify the time unit. (5s, 1m...) this form doesn't fit with the flag's name(timeout-'second'.)

ETCD endpoints don't be assigned directly too. Because etcd config's pointer is nil for default. 
 
This PR adds command-line flags(long flags only).

 

**Does this PR introduce a user-facing change?**:

```release-note
Add flags that can set all configurations of Agent
```

**Additional documentation**:

```docs

```

**Checklist**:
- [x] Added relevant tests or not required
- [x] Didn't break anything

2021-03-29 01:20 UTC, hackerwins requested changes
Thanks for the contribution. I've commented on some things that need to be fixed.

2021-03-29 01:20 UTC, hackerwins commented on pkg/cli/agent.go
> +		yorkie.DefaultMongoConnectionURI,
```suggestion
		yorkie.DefaultMongoYorkieDatabase,
```

2021-03-29 01:20 UTC, hackerwins commented on pkg/cli/agent.go
> +			//if config file is given, command-line argumentes will be overwritten
```suggestion
			// If config file is given, command-line arguments will be overwritten.
```

2021-03-29 01:20 UTC, hackerwins commented on pkg/cli/agent.go
>  		"config path",
```suggestion
		"Config path",
```

2021-03-29 01:20 UTC, hackerwins commented on pkg/cli/agent.go
> +		"metrics port",
```suggestion
		"Metrics port",
```

2021-03-29 01:35 UTC, hackerwins commented
It would be nice to consider changing the `timeout-second` variable to duration as well. We can easily convert it using [ParseDuration](https://golang.org/pkg/time/#ParseDuration).

I think it's good to start with a separate issue.

2021-03-29 14:09 UTC, dc7303 requested changes
Thanks for working.
I'd like to ask for a change, so I left a comment. Please confirm.

2021-03-29 14:09 UTC, dc7303 commented on pkg/cli/agent.go
> +		"MongoDB's connection URI",
```suggestion
		"Yorkie's database name in MongoDB",
```

2021-03-30 00:20 UTC, hackerwins approved these changes
LGTM. Thank you for contributing.

2021-03-30 00:21 UTC, merged