apply changes incrementally
yorkie-team/yorkie pull request #244
Opened 2021-08-30 16:25 UTC by codinggosu

**What this PR does / why we need it**:
loads changes incrementally, as described in issue #228 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

This is a draft PR, just to make sure that this is the direction that this issue should be headed for.

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation**:

```docs

```

**Checklist**:
- [ ] Added relevant tests or not required
- [x] Didn't break anything

2021-08-30 16:26 UTC, codinggosu commented on yorkie/packs/packs.go
> +	var startIdx, endIdx = 0, CHANGE_SEGMENT_SIZE;
I haven't verified the logic of this, just wanted to make sure that this is indeed the right direction, before further implementation and testing

2021-09-01 01:19 UTC, hackerwins commented on yorkie/packs/packs.go
> +const CHANGE_SEGMENT_SIZE = 100
Please refer to the document below.
https://github.com/yorkie-team/yorkie/blob/main/CONTRIBUTING.md#code-style

2021-09-01 07:21 UTC, hackerwins commented
Thank you for your contribution. I think the approach is good.

There are still many changes that need to be fetched from the DB. It seems that we need to include code to fetch from DB in the loop.

2021-09-01 08:47 UTC, codinggosu commented on yorkie/packs/packs.go
> +const CHANGE_SEGMENT_SIZE = 100
Thank you for the comment! As this was a draft PR mainly aimed at verifying the direction of the change, I didn't look too closely at the coding style. 
I will make sure to clean up all the code thoroughly and in accordance with the guide before the final change.

2021-09-24 15:23 UTC, codinggosu commented
I will look over and test the code again with edge cases and edge values. 
After testing, I will mark the PR as ready!

2021-10-06 02:39 UTC, hackerwins requested changes
Thanks for your contribution.

Is it possible to write test code for this code?

2021-10-06 02:39 UTC, hackerwins commented on yorkie/packs/packs.go
>  	}
How about using a for loop a little more to shorten the code?

```suggestion
	for startIdx := snapshotInfo.ServerSeq + 1; startIdx < initialServerSeq; startIdx += changeSegmentSize {
		var endIdx uint64
		if startIdx+changeSegmentSize < initialServerSeq {
			endIdx = startIdx + changeSegmentSize
		} else {
			endIdx = initialServerSeq
		}

		changes, err := be.DB.FindChangeInfosBetweenServerSeqs(
			ctx,
			docInfo.ID,
			startIdx,
			endIdx,
		)
		if err != nil {
			return nil, nil, err
		}

		if err := doc.ApplyChangePack(change.NewPack(
			docKey,
			checkpoint.Initial.NextServerSeq(docInfo.ServerSeq),
			changes,
			nil,
		)); err != nil {
			return nil, nil, err
		}
	}
```

2021-10-06 05:03 UTC, codinggosu commented
yes! I will add test code and update the pr

2021-10-31 13:12 UTC, codinggosu commented
unfortunately, I can't find time to work on this issue anymore
I regret it, but it seems better to close this pr for now.

2021-10-31 13:12 UTC, closed without merging

2021-10-31 13:16 UTC, hackerwins commented
Good luck to you.