Add benchmarks (#180)
yorkie-team/yorkie pull request #246
Opened 2021-09-14 08:43 UTC by zeikar

**What this PR does / why we need it**:
Benchmark operations of the document.

**Which issue(s) this PR fixes**:

Fixes #180 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation**:

```docs
editing-trace.json is based on https://github.com/automerge/automerge-perf.
```

**Checklist**:

2021-09-14 08:50 UTC, zeikar commented
If you run BenchmarkEditing (about 200,000 data), it won't finish even if you run it for several hours.
So, it is necessary to check whether the benchmark is properly implemented.
If the benchmark code is ok, it seems that Yorkie has performance issues.

2021-09-18 08:09 UTC, dc7303 commented
When I run the `make bench` command, an error occurs.  This is happening when I add the `-bench` option on running the go test. 😨
Are any other reviewers okay? First, I'll fix this issue and do a review...

```bash
go test -tags bench -bench=./test/bench
no Go files in /Users/scott/Workspace/dc7303/yorkie
make: *** [bench] Error 1
```

2021-09-29 05:00 UTC, hackerwins commented
@dc7303

We can run benchs like below.

```bash
cd test/bench
go test -tags=bench -bench=.
```

2021-09-29 05:12 UTC, hackerwins requested changes
Thanks for your contribution. It would be good to register additional issues to find bottlenecks on the bench.

I left a brief comment.

2021-09-29 05:12 UTC, hackerwins commented on Makefile
> +	go test -tags bench -bench=./test/bench
```suggestion
	go test -tags bench -bench=. ./test/bench
```

2021-09-29 05:53 UTC, hackerwins commented on test/bench/editing_bench_test.go
> +func BenchmarkEditing(b *testing.B) {
```suggestion
func BenchmarkTextEditing(b *testing.B) {
```

2021-09-29 15:11 UTC, zeikar commented
@hackerwins 
Thank you for your reviews. I have committed all your suggestions.

2021-10-03 12:05 UTC, hackerwins approved these changes
Thanks for your contribution.

The test code doesn't seem to have any issues. I found an issue with a linear increase in execution time when running text edits.

```bash
    editing_bench_test.go:86: processing... 1000 833.432413ms
    editing_bench_test.go:86: processing... 2000 2.486363836s
    editing_bench_test.go:86: processing... 3000 3.766670666s
    editing_bench_test.go:86: processing... 4000 5.264808552s
    editing_bench_test.go:86: processing... 5000 7.45837556s
    ...
```

It might be a good idea to create a separate issue that finds the cause of this problem and fixes it.

2021-10-03 12:05 UTC, merged