Implement gRPC benchmark test
yorkie-team/yorkie pull request #348
Opened 2022-06-28 10:04 UTC by DongjinS

**What this PR does / why we need it**:

Implement gRPC benchmark test but "client to client via server" test has an error.  
I'll fix it before the opening this PR.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation**:

```docs

```

**Checklist**:
- [ ] Added relevant tests or not required
- [ ] Didn't break anything

2022-06-29 08:57 UTC, DongjinS commented
@hackerwins I find `logging.SetLogLevel( )` in logging.go which change log level. thanks for comments 👍

2022-06-30 02:06 UTC, DongjinS commented
In test:`attach large document`, 
When the size of the document is larger than a certain amount, the error will occur, so I tested it with a size that does not cause any errors.

I attach a picture of the error that occurred.
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/46275039/176577054-3f40d28b-7e22-4447-be1c-8d037aecf141.png">

2022-06-30 02:09 UTC, hackerwins commented
@DongjinS This error seems to be related to MaxRequestBytes.

https://github.com/yorkie-team/yorkie/blob/147cd1fcf2d320d01bb7ab95eb3d2643f3c4875d/server/rpc/server.go#L75

2022-06-30 02:12 UTC, hackerwins requested changes
Thanks for your contribution.
I left comments.

2022-06-30 02:12 UTC, hackerwins commented on test/bench/grpc_bench_test.go
> + * Copyright 2021 The Yorkie Authors. All rights reserved.
```suggestion
 * Copyright 2022 The Yorkie Authors. All rights reserved.
```

2022-06-30 02:12 UTC, hackerwins commented on test/bench/grpc_bench_test.go
> +	// "unsafe"
```suggestion
```

2022-06-30 02:12 UTC, hackerwins commented on test/bench/grpc_bench_test.go
> +			b.StartTimer()
This code doesn't seem to work as intended. Let's remove b.StopTimer and b.StartTimer for now.

```suggestion
			b.StartTimer()
```

2022-06-30 10:24 UTC, hackerwins approved these changes
Thanks for your contribution. 👍

2022-06-30 10:24 UTC, merged

2022-07-01 01:00 UTC, DongjinS commented
@hackerwins 
Even after changing to MaxRequestBytes 10Mib, the "ResourceExhausted" error still occurs depending on the "builder" size of the "attach large document test".
I am attaching pictures below.
1) Error condition: MaxRequestBytes = 10Mib, builder size = 10485760
![image](https://user-images.githubusercontent.com/46275039/176801834-4c18b396-a345-43ee-bdee-28a8323db6d2.png)
2) Error condition:  MaxRequestBytes = 10Mib, builder size = 10000000
![image](https://user-images.githubusercontent.com/46275039/176801846-4320b797-89e6-4edc-bea3-44aebf5993cb.png)