Remove panic from crdt counter
yorkie-team/yorkie pull request #598
Opened 2023-08-04 08:40 UTC by MoonGyu1

**What this PR does / why we need it**:

Remove the panic methods in `crdt/counter.go`
- Before, there were panic methods to reveal errors in development environment, but because it risks stopping the server in production, so those panics were replaced with error methods.
- As the panic methods in counter were replaced, the related test codes also were modified.

**Which issue(s) this PR fixes**:

Related to [#497](https://github.com/yorkie-team/yorkie/issues/497#issuecomment-1617477643) (`crdt/counter`)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation**:

```docs

```

**Checklist**:
- [x] Added relevant tests or not required
- [x] Didn't break anything

2023-08-04 08:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yorkie-team/yorkie?pullRequest=598) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yorkie-team/yorkie?pullRequest=598) before we can accept your contribution.<br/><hr/>**USER** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yorkie-team/yorkie?pullRequest=598) it.</sub>

2023-08-06 04:19 UTC, krapie submitted a review, later dismissed
Thank you for your contribution 👍🏼 

I left a small comment below.

2023-08-06 04:19 UTC, krapie commented on pkg/document/crdt/counter.go
> +		return nil, fmt.Errorf("unsupported type")
Since `unsupported type` error message is used in several other places, how about constantize this to something like `ErrUnsupportedType`?

2023-08-06 04:23 UTC, krapie requested changes
Follow above comment 😅

2023-08-07 02:31 UTC, hackerwins approved these changes
Thanks for your contribution. 👍

2023-08-07 02:32 UTC, merged