Add Helm chart for MongoDB sharded cluster
yorkie-team/yorkie pull request #769
Opened 2024-01-19 13:12 UTC by sejongk

**What this PR does / why we need it**:
This PR adds a Helm chart for MongoDB sharded clusters.
Shard rules, including shard keys, shard methods, and unique constraints, are defined and managed in the `values.yaml`.

This chart depends on the Bitnami's `mongodb-sharded` chart (https://github.com/bitnami/charts/tree/main/bitnami/mongodb-sharded).
There are a few known issues with it:
- A problem with livenessProbe and readinessProbe
  - https://github.com/bitnami/charts/issues/21957
- Lack of ARM64 support in the Bitnami `mongodb-sharded` **container**
  - https://github.com/bitnami/charts/issues/7305#issuecomment-1443187343
  - https://github.com/bitnami/containers/issues/40947

**Which issue(s) this PR fixes**:

Addresses #673 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation**:

```docs

```

**Checklist**:
- [ ] Added relevant tests or not required
- [ ] Didn't break anything

2024-01-24 07:50 UTC, hackerwins requested changes
Thanks for your contribution.
I left a few comments.

2024-01-24 07:50 UTC, hackerwins commented on build/charts/yorkie-mongodb/templates/sharded/configmap.yaml
> +
```suggestion
    
```

2024-01-24 07:50 UTC, hackerwins commented on build/charts/yorkie-mongodb/values.yaml
> +image:
Could you add descriptions for each section(image, persistence, sharded, and mongodb-sharded)?

2024-01-24 14:30 UTC, krapie reviewed
Thank you for your contribution 😄
First off, I have left some small conventional suggestions along with comprehensive questions.

#### Question 1

It seems like `yorkie-cluster` Helm chart no longer has mongoDB subshart. This means that we now need to install both `yorkie-cluster` and `yorkie-mongodb` Helm chart to fully use yorkie cluster. Is there any reason for this separation?

#### Question 2

It seems like `yorkie-mongodb` Helm chart performs sharded mongoDB setup by using Job object. Is there any reason for this approach?

I can see that mongodb-sharded Helm chart provides `common.initScriptsCM` value to initialize mongoDB instances (Nevertheless [I also think using Job is the best approach for this kind of operation](https://github.com/docker-library/mongo/issues/339#issuecomment-1276780427), I just want to know the reasons for this approach).

> Lack of ARM64 support in the Bitnami mongodb-sharded container
> Solution: use the official mongo 6.0 image instead and set up the cluster via a Job.

Also, is there any relations between ARM64 support and setting up cluster via Job?

#### Suggestion 3

How about adding [`NOTES.txt`](https://github.com/yorkie-team/yorkie/blob/main/build/charts/yorkie-cluster/templates/NOTES.txt) to keep consistency with other yorkie Helm charts?

#### Suggestion 4

We might need to add [ArgoCD application manifest](https://github.com/yorkie-team/yorkie/blob/main/build/charts/yorkie-argocd/templates/applications.yaml) for `yorkie-mongodb` in `yorkie-argocd` Helm chart.

2024-01-25 10:35 UTC, krapie approved these changes
LGTM 👍🏼

2024-01-25 10:35 UTC, hackerwins approved these changes
LGTM.

2024-01-25 10:39 UTC, merged

2024-01-25 15:24 UTC, sejongk commented
> #### Question 1
> It seems like `yorkie-cluster` Helm chart no longer has mongoDB subshart. This means that we now need to install both `yorkie-cluster` and `yorkie-mongodb` Helm chart to fully use yorkie cluster. Is there any reason for this separation?
> 
> #### Question 2
> It seems like `yorkie-mongodb` Helm chart performs sharded mongoDB setup by using Job object. Is there any reason for this approach?
> 
> I can see that mongodb-sharded Helm chart provides `common.initScriptsCM` value to initialize mongoDB instances (Nevertheless [I also think using Job is the best approach for this kind of operation](https://github.com/docker-library/mongo/issues/339#issuecomment-1276780427), I just want to know the reasons for this approach).
> 
> > Lack of ARM64 support in the Bitnami mongodb-sharded container
> > Solution: use the official mongo 6.0 image instead and set up the cluster via a Job.
> 
> Also, is there any relations between ARM64 support and setting up cluster via Job?

Thanks for your careful review.
Here are my answers for your questions.

#### Answer 1
After separating MongoDB from yorkie-cluster, there are now two options for users: self-hosted or managed databases (e.g., MongoDB Atlas, AWS DynamoDB). I believe we can focus on supporting self-hosted clusters by solely maintaining yorkie-mongodb.

#### Answer 2
I initially explored the approach using Bitnami options and tools. Bitnami charts are designed to be used with Bitnami containers together. However, issues arose, including the lack of ARM64 images in the Bitnami `mongodb-sharded` container. Instead of incurring the current and potential future engineering costs associated with external tools, I opted to implement and maintain the code ourselves. 
I believe the current requirements for this are relatively simple and manageable. If future requirements become more complex and there is a good alternative, that would be the time to consider such an option.